//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NES.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrgUnit_Department
    {
        public int OrgUnitID { get; set; }
        public int DepartmentID { get; set; }
        public int OrgDepID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual OrgUnit OrgUnit { get; set; }
    }
}
