//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NES.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserEntities : DbContext
    {
        public UserEntities()
            : base("name=UserEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<OrgUnit> OrgUnit { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<UserDepartmentView> UserDepartmentView { get; set; }
        public virtual DbSet<UserPositionView> UserPositionView { get; set; }
        public virtual DbSet<Department_Position> Department_Position { get; set; }
        public virtual DbSet<OrgUnit_Department> OrgUnit_Department { get; set; }
        public virtual DbSet<DepartmentPositionView> DepartmentPositionView { get; set; }
        public virtual DbSet<OrgUnitDepartmentView> OrgUnitDepartmentView { get; set; }
    }
}
