//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NES.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class UserLoginView
    {
        public int UserID { get; set; }

        [DisplayName("User Name")]
        [StringLength(50, MinimumLength = 4, ErrorMessage = "Must be 4 to 50 chars!")]
        [Required(ErrorMessage = "Required field!")]
        public string UserName { get; set; }

        [DataType(DataType.Password)]
        [StringLength(50, MinimumLength = 4, ErrorMessage = "Must be 4 to 50 chars!")]
        [Required(ErrorMessage = "Required field!")]
        public string Password { get; set; }

        public string FirstName { get; set; }
        public string LastName { get; set; }
        public bool IsActivated { get; set; }

        public string LoginErrorMsg { get; set; }
    }
}
